// src/lib/components/Header.svelte
<script lang="ts">
	import { m } from '$lib/paraglide/messages.js';
	import { getLocale, setLocale } from '$lib/paraglide/runtime';

	let isMenuOpen = $state(false);
	let scrollY = $state(0);

	const navLinks = [
		{ label: () => m.nav_about(), href: '#about' },
		{ label: () => m.nav_projects(), href: '#projects' },
		{ label: () => m.nav_experience(), href: '#experience' },
		{ label: () => m.nav_contact(), href: '#contact' },
		{ label: () => m.nav_veille(), href: '/veille', isPage: true }
	];

	const toggleLocale = () => {
		const currentLocale = getLocale();
		setLocale(currentLocale === 'en' ? 'fr' : 'en');
	};

	const handleNavClick = (href: string) => {
		const element = document.querySelector(href);
		if (element) {
			element.scrollIntoView({ behavior: 'smooth' });
			isMenuOpen = false;
		}
	};

	const toggleMenu = () => {
		isMenuOpen = !isMenuOpen;
	};

	// Reactive shadow based on scroll
	const headerShadow = $derived(
		scrollY > 100 ? '0px 4px 12px 0px rgba(17, 24, 39, 0.1)' : '0px 0px 0px 0px rgba(17, 24, 39, 0)'
	);
</script>

<svelte:window bind:scrollY />

<header class="header" style:box-shadow={headerShadow}>
	<nav class="nav">
		<!-- Logo -->
		<div class="logo">
			<button aria-label="Go to top" onclick={() => handleNavClick('#hero')} type="button">
				<span class="logo-text">TOM</span>.
			</button>
		</div>

		<!-- Desktop Navigation -->
		<div class="nav-desktop">
			{#each navLinks as link (link.href)}
				{#if link.isPage}
					<a href={link.href} class="nav-link">
						{link.label()}
						<span class="nav-link-underline"></span>
					</a>
				{:else}
					<button type="button" class="nav-link" onclick={() => handleNavClick(link.href)}>
						{link.label()}
						<span class="nav-link-underline"></span>
					</button>
				{/if}
			{/each}
			<button
				aria-label="Toggle language"
				class="locale-toggle"
				onclick={toggleLocale}
				type="button"
			>
				{getLocale().toUpperCase()}
			</button>
		</div>

		<!-- Mobile Menu Button -->
		<div class="mobile-controls">
			<button
				aria-label="Toggle language"
				class="locale-toggle"
				onclick={toggleLocale}
				type="button"
			>
				{getLocale().toUpperCase()}
			</button>
			<button
				aria-label={isMenuOpen ? 'Close menu' : 'Open menu'}
				class="menu-toggle"
				onclick={toggleMenu}
				type="button"
			>
				{#if isMenuOpen}
					<svg
						xmlns="http://www.w3.org/2000/svg"
						width="24"
						height="24"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
					>
						<line x1="18" y1="6" x2="6" y2="18"></line>
						<line x1="6" y1="6" x2="18" y2="18"></line>
					</svg>
				{:else}
					<svg
						xmlns="http://www.w3.org/2000/svg"
						width="24"
						height="24"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
					>
						<line x1="3" y1="12" x2="21" y2="12"></line>
						<line x1="3" y1="6" x2="21" y2="6"></line>
						<line x1="3" y1="18" x2="21" y2="18"></line>
					</svg>
				{/if}
			</button>
		</div>
	</nav>

	<!-- Mobile Navigation -->
	<div class="nav-mobile" class:open={isMenuOpen}>
		<div class="nav-mobile-content">
			{#each navLinks as link, index (link.href)}
				{#if link.isPage}
					<a href={link.href} class="nav-mobile-link" style:animation-delay="{index * 50}ms">
						{link.label()}
					</a>
				{:else}
					<button
						type="button"
						class="nav-mobile-link"
						onclick={() => handleNavClick(link.href)}
						style:animation-delay="{index * 50}ms"
					>
						{link.label()}
					</button>
				{/if}
			{/each}
		</div>
	</div>
</header>

<style lang="scss">
	// Variables
	$color-gray-700: #374151;
	$color-gray-900: #111827;
	$color-cyan-50: #ecfeff;
	$color-cyan-100: #cffafe;
	$color-cyan-600: #0891b2;
	$color-rose-600: #e11d48;
	$color-white: #ffffff;

	$breakpoint-sm: 640px;
	$breakpoint-md: 768px;
	$breakpoint-lg: 1024px;
	$breakpoint-xl: 1280px;
	$breakpoint-2xl: 1536px;

	$transition-fast: 0.2s ease;
	$transition-normal: 0.3s ease;

	// Header
	.header {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		z-index: 50;
		background-color: rgba($color-white, 0.8);
		backdrop-filter: blur(12px);
		border-bottom: 2px solid $color-gray-900;
		animation: slideDown 0.6s ease-out;
	}

	@keyframes slideDown {
		from {
			transform: translateY(-100%);
		}
		to {
			transform: translateY(0);
		}
	}

	// Navigation
	.nav {
		display: flex;
		align-items: center;
		justify-content: space-between;
		max-width: 1280px;
		margin: 0 auto;
		padding: 0.75rem 1rem;

		@media (min-width: $breakpoint-sm) {
			padding: 1rem 1.5rem;
		}

		@media (min-width: $breakpoint-lg) {
			padding: 1rem 2rem;
		}

		@media (min-width: $breakpoint-xl) {
			max-width: 1400px;
		}

		@media (min-width: $breakpoint-2xl) {
			max-width: 1600px;
		}
	}

	// Logo
	.logo {
		animation: fadeInLeft 0.5s ease-out;

		button {
			background: none;
			border: none;
			cursor: pointer;
			font-family: inherit;
			font-size: 1.25rem;
			font-weight: 900;
			color: $color-gray-900;

			@media (min-width: $breakpoint-sm) {
				font-size: 1.5rem;
			}

			@media (min-width: $breakpoint-xl) {
				font-size: 1.875rem;
			}
		}
	}

	.logo-text {
		position: relative;
		display: inline-block;

		// Texte de base (visible par défaut)
		&::before {
			content: 'TOM';
			position: absolute;
			left: 0;
			top: 0;
			background: linear-gradient(to right, $color-cyan-600, $color-rose-600);
			-webkit-background-clip: text;
			background-clip: text;
			color: transparent;
			opacity: 0;
			transition: opacity $transition-normal;
		}

		.logo button:hover &::before {
			opacity: 1;
		}
	}

	@keyframes fadeInLeft {
		from {
			opacity: 0;
			transform: translateX(-20px);
		}
		to {
			opacity: 1;
			transform: translateX(0);
		}
	}

	// Desktop Navigation
	.nav-desktop {
		display: none;
		align-items: center;
		gap: 1.5rem;
		animation: fadeInDown 0.5s ease-out 0.1s both;

		@media (min-width: $breakpoint-md) {
			display: flex;
		}

		@media (min-width: $breakpoint-xl) {
			gap: 2rem;
		}

		@media (min-width: $breakpoint-2xl) {
			gap: 2.5rem;
		}
	}

	@keyframes fadeInDown {
		from {
			opacity: 0;
			transform: translateY(-10px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}

	.nav-link {
		position: relative;
		background: none;
		border: none;
		cursor: pointer;
		font-family: inherit;
		font-size: 0.875rem;
		font-weight: 700;
		color: $color-gray-700;
		text-decoration: none;
		transition: $transition-fast;
		padding: 0.25rem 0;

		@media (min-width: $breakpoint-sm) {
			font-size: 1rem;
		}

		@media (min-width: $breakpoint-xl) {
			font-size: 1.125rem;
		}

		&:hover {
			color: $color-gray-900;
			transform: translateY(-2px);
		}

		&:active {
			transform: scale(0.95);
		}
	}

	.nav-link-underline {
		position: absolute;
		bottom: -2px;
		left: 0;
		width: 0;
		height: 2px;
		background-color: $color-cyan-600;
		transition: width $transition-normal;

		.nav-link:hover & {
			width: 100%;
		}
	}

	// Locale Toggle
	.locale-toggle {
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 0.375rem 0.75rem;
		background: linear-gradient(to right, $color-cyan-50, $color-cyan-100);
		border: 2px solid $color-gray-900;
		border-radius: 0.5rem;
		cursor: pointer;
		font-family: inherit;
		font-size: 0.75rem;
		font-weight: 900;
		color: $color-gray-900;
		transition: $transition-fast;

		@media (min-width: $breakpoint-sm) {
			padding: 0.5rem 1rem;
			font-size: 0.875rem;
		}

		@media (min-width: $breakpoint-xl) {
			font-size: 1rem;
		}

		&:hover {
			background: linear-gradient(to right, $color-cyan-100, $color-cyan-600);
			color: $color-white;
			transform: scale(1.05);
		}

		&:active {
			transform: scale(0.95);
		}
	}

	// Mobile Controls
	.mobile-controls {
		display: flex;
		align-items: center;
		gap: 0.75rem;

		@media (min-width: $breakpoint-md) {
			display: none;
		}
	}

	.menu-toggle {
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 0.5rem;
		background-color: $color-white;
		border: 2px solid $color-gray-900;
		border-radius: 0.5rem;
		cursor: pointer;
		color: $color-gray-900;
		transition: $transition-fast;
		animation: fadeInRight 0.5s ease-out;

		@media (min-width: $breakpoint-sm) {
			padding: 0.625rem;
		}

		&:hover {
			transform: scale(1.05);
		}

		&:active {
			transform: scale(0.95);
		}
	}

	@keyframes fadeInRight {
		from {
			opacity: 0;
			transform: translateX(20px);
		}
		to {
			opacity: 1;
			transform: translateX(0);
		}
	}

	// Mobile Navigation
	.nav-mobile {
		display: block;
		max-height: 0;
		overflow: hidden;
		opacity: 0;
		transition:
			max-height $transition-normal,
			opacity $transition-normal;

		@media (min-width: $breakpoint-md) {
			display: none;
		}

		&.open {
			max-height: 400px;
			opacity: 1;
		}
	}

	.nav-mobile-content {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
		padding: 1rem;
		background-color: $color-white;
		border-top: 2px solid $color-gray-900;

		@media (min-width: $breakpoint-sm) {
			padding: 1rem 1.5rem;
		}
	}

	.nav-mobile-link {
		display: block;
		width: 100%;
		padding: 0.75rem 1rem;
		background-color: $color-cyan-50;
		border: 2px solid $color-gray-900;
		border-radius: 0.5rem;
		cursor: pointer;
		text-align: left;
		text-decoration: none;
		font-family: inherit;
		font-size: 0.875rem;
		font-weight: 700;
		color: $color-gray-900;
		transition: $transition-fast;
		opacity: 0;
		transform: translateX(-20px);

		.nav-mobile.open & {
			animation: slideInLeft 0.3s ease-out forwards;
		}

		@media (min-width: $breakpoint-sm) {
			font-size: 1rem;
		}

		&:hover {
			background-color: $color-cyan-100;
			transform: translateX(4px);
		}

		&:active {
			transform: scale(0.98);
		}
	}

	@keyframes slideInLeft {
		from {
			opacity: 0;
			transform: translateX(-20px);
		}
		to {
			opacity: 1;
			transform: translateX(0);
		}
	}
</style>

// src/components/layout/Header.tsx
"use client";

import { Menu, X } from "lucide-react";
import { motion, useScroll, useTransform } from "motion/react";
import { memo, useState } from "react";

interface NavLink {
	label: string;
	href: string;
}

const NAV_LINKS: NavLink[] = [
	{ label: "About", href: "#about" },
	{ label: "Skills", href: "#skills" },
	{ label: "Projects", href: "#projects" },
	{ label: "Experience", href: "#experience" },
	{ label: "Contact", href: "#contact" },
];

export const Header = memo(() => {
	const [isMenuOpen, setIsMenuOpen] = useState(false);
	const { scrollY } = useScroll();

	// Header background and shadow appear on scroll
	const headerBackground = useTransform(
		scrollY,
		[0, 100],
		["rgba(255, 255, 255, 0)", "rgba(255, 255, 255, 0.95)"],
	);

	const headerShadow = useTransform(
		scrollY,
		[0, 100],
		["0px 0px 0px 0px rgba(17,24,39,0)", "0px 4px 12px 0px rgba(17,24,39,0.1)"],
	);

	const handleNavClick = (href: string) => {
		const element = document.querySelector(href);
		if (element) {
			element.scrollIntoView({ behavior: "smooth" });
			setIsMenuOpen(false);
		}
	};

	return (
		<motion.header
			className="fixed top-0 z-50 w-full border-gray-900 border-b-2 backdrop-blur-md"
			style={{
				backgroundColor: headerBackground,
				boxShadow: headerShadow,
			}}
			initial={{ y: -100 }}
			animate={{ y: 0 }}
			transition={{ duration: 0.6, ease: "easeOut" }}
		>
			<nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6 sm:py-4 lg:px-8 xl:max-w-[1400px] 2xl:max-w-[1600px]">
				{/* Logo */}
				<motion.div
					className="flex items-center"
					initial={{ opacity: 0, x: -20 }}
					animate={{ opacity: 1, x: 0 }}
					transition={{ duration: 0.5 }}
				>
					<button
						type="button"
						onClick={() => handleNavClick("#hero")}
						className="font-black text-gray-900 text-xl transition-colors hover:text-cyan-600 sm:text-2xl xl:text-3xl"
						aria-label="Go to top"
					>
						TOM<span className="text-cyan-600">.</span>
					</button>
				</motion.div>

				{/* Desktop Navigation */}
				<motion.div
					className="hidden items-center gap-6 md:flex xl:gap-8 2xl:gap-10"
					initial={{ opacity: 0, y: -10 }}
					animate={{ opacity: 1, y: 0 }}
					transition={{ duration: 0.5, delay: 0.1 }}
				>
					{NAV_LINKS.map((link, index) => (
						<motion.button
							key={link.href}
							onClick={() => handleNavClick(link.href)}
							className="group relative font-bold text-gray-700 text-sm transition-colors hover:text-gray-900 sm:text-base xl:text-lg"
							initial={{ opacity: 0, y: -10 }}
							animate={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.5, delay: 0.1 + index * 0.05 }}
							whileHover={{ y: -2 }}
							whileTap={{ scale: 0.95 }}
						>
							{link.label}
							<span className="-bottom-1 absolute left-0 h-0.5 w-0 bg-cyan-600 transition-all duration-300 group-hover:w-full" />
						</motion.button>
					))}
				</motion.div>

				{/* Mobile Menu Button */}
				<motion.button
					className="rounded-lg border-2 border-gray-900 bg-white p-2 text-gray-900 sm:p-2.5 md:hidden"
					onClick={() => setIsMenuOpen(!isMenuOpen)}
					initial={{ opacity: 0, x: 20 }}
					animate={{ opacity: 1, x: 0 }}
					transition={{ duration: 0.5 }}
					whileHover={{ scale: 1.05 }}
					whileTap={{ scale: 0.95 }}
					aria-label={isMenuOpen ? "Close menu" : "Open menu"}
				>
					{isMenuOpen ? (
						<X size={24} className="sm:h-6 sm:w-6" />
					) : (
						<Menu size={24} className="sm:h-6 sm:w-6" />
					)}
				</motion.button>
			</nav>

			{/* Mobile Navigation */}
			<motion.div
				className="md:hidden"
				initial={false}
				animate={{
					height: isMenuOpen ? "auto" : 0,
					opacity: isMenuOpen ? 1 : 0,
				}}
				transition={{ duration: 0.3, ease: "easeInOut" }}
				style={{ overflow: "hidden" }}
			>
				<div className="space-y-2 border-gray-900 border-t-2 bg-white px-4 py-4 sm:px-6">
					{NAV_LINKS.map((link, index) => (
						<motion.button
							key={link.href}
							onClick={() => handleNavClick(link.href)}
							className="block w-full rounded-lg border-2 border-gray-900 bg-cyan-50 px-4 py-3 text-left font-bold text-gray-900 text-sm transition-colors hover:bg-cyan-100 sm:text-base"
							initial={{ opacity: 0, x: -20 }}
							animate={{
								opacity: isMenuOpen ? 1 : 0,
								x: isMenuOpen ? 0 : -20,
							}}
							transition={{
								duration: 0.3,
								delay: isMenuOpen ? index * 0.05 : 0,
							}}
							whileHover={{ x: 4 }}
							whileTap={{ scale: 0.98 }}
						>
							{link.label}
						</motion.button>
					))}
				</div>
			</motion.div>
		</motion.header>
	);
});

Header.displayName = "Header";
