// app/sections/Hero.tsx
"use client";

import { ChevronDown, Zap } from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { HERO_STATS, SOCIAL_LINKS } from "@/data/constants";

function StatCard({ value, label }: { value: string; label: string }) {
	return (
		<div className="rounded-2xl border-2 border-gray-300 bg-white/90 p-3 text-center shadow-sm transition-all sm:p-4">
			<div className="font-black text-gray-900 text-xl sm:text-2xl">
				{value}
			</div>
			<div className="font-bold text-gray-600 text-xs sm:text-sm">{label}</div>
		</div>
	);
}

function SocialLinks() {
	return (
		<div className="flex gap-4">
			{SOCIAL_LINKS.map((social, index) => {
				const Icon = social.icon;
				return (
					<motion.a
						key={social.label}
						href={social.href}
						target="_blank"
						rel="noopener noreferrer"
						className={`flex h-14 w-14 items-center justify-center rounded-xl border-3 border-gray-900 bg-white text-gray-900 shadow-[4px_4px_0px_0px_rgba(17,24,39,1)] transition-all md:border-4 ${social.color}`}
						initial={{ opacity: 0, y: 20 }}
						animate={{ opacity: 1, y: 0 }}
						transition={{ duration: 0.5, delay: 0.6 + index * 0.1 }}
						whileHover={{
							y: -4,
							boxShadow: "6px 6px 0px 0px rgba(17,24,39,1)",
							transition: { duration: 0.2 },
						}}
						whileTap={{
							y: 0,
							boxShadow: "2px 2px 0px 0px rgba(17,24,39,1)",
							transition: { duration: 0.1 },
						}}
						aria-label={social.label}
					>
						<Icon size={24} />
					</motion.a>
				);
			})}
		</div>
	);
}

function FloatingShapes() {
	return (
		<>
			{/* Circle 1 */}
			<motion.div
				className="absolute top-20 left-10 h-24 w-24 rounded-full bg-cyan-300 opacity-30 blur-sm"
				animate={{
					y: [0, -30, 0],
					x: [0, 20, 0],
					rotate: [0, 180, 360],
				}}
				transition={{
					duration: 15,
					repeat: Number.POSITIVE_INFINITY,
					ease: "easeInOut",
				}}
				style={{ zIndex: -1 }}
			/>

			{/* Square 1 */}
			<motion.div
				className="absolute top-40 right-20 h-32 w-32 rotate-45 bg-rose-300 opacity-25 blur-sm"
				animate={{
					y: [0, 40, 0],
					x: [0, -30, 0],
					rotate: [45, 135, 45],
				}}
				transition={{
					duration: 20,
					repeat: Number.POSITIVE_INFINITY,
					ease: "easeInOut",
				}}
				style={{ zIndex: -1 }}
			/>

			{/* Circle 2 */}
			<motion.div
				className="absolute bottom-32 left-1/4 h-20 w-20 rounded-full bg-cyan-400 opacity-35 blur-sm"
				animate={{
					y: [0, 25, 0],
					x: [0, -15, 0],
					scale: [1, 1.2, 1],
				}}
				transition={{
					duration: 12,
					repeat: Number.POSITIVE_INFINITY,
					ease: "easeInOut",
				}}
				style={{ zIndex: -1 }}
			/>

			{/* Triangle (using clip-path) */}
			<motion.div
				className="absolute right-1/4 bottom-40 h-28 w-28 bg-rose-400 opacity-30 blur-sm"
				style={{
					clipPath: "polygon(50% 0%, 0% 100%, 100% 100%)",
					zIndex: -1,
				}}
				animate={{
					y: [0, -35, 0],
					x: [0, 25, 0],
					rotate: [0, 120, 240, 360],
				}}
				transition={{
					duration: 18,
					repeat: Number.POSITIVE_INFINITY,
					ease: "easeInOut",
				}}
			/>
		</>
	);
}

function ScrollIndicator() {
	const [isVisible, setIsVisible] = useState(true);

	useEffect(() => {
		const handleScroll = () => {
			if (window.scrollY > 100) {
				setIsVisible(false);
			} else {
				setIsVisible(true);
			}
		};

		window.addEventListener("scroll", handleScroll);
		return () => window.removeEventListener("scroll", handleScroll);
	}, []);

	const handleClick = () => {
		document.getElementById("about")?.scrollIntoView({
			behavior: "smooth",
		});
	};

	return (
		<AnimatePresence>
			{isVisible && (
				<motion.button
					onClick={handleClick}
					className="-translate-x-1/2 absolute bottom-8 left-1/2 cursor-pointer"
					initial={{ opacity: 0 }}
					animate={{ opacity: 1 }}
					exit={{ opacity: 0 }}
					transition={{ duration: 0.3 }}
					aria-label="Scroll to about section"
				>
					<motion.div
						animate={{
							y: [0, 10, 0],
						}}
						transition={{
							duration: 2,
							repeat: Number.POSITIVE_INFINITY,
							ease: "easeInOut",
						}}
					>
						<ChevronDown
							className="h-8 w-8 text-gray-900 sm:h-10 sm:w-10"
							strokeWidth={3}
						/>
					</motion.div>
				</motion.button>
			)}
		</AnimatePresence>
	);
}

export function Hero() {
	const { t } = useTranslation();

	return (
		<section
			id="hero"
			className="relative flex min-h-screen items-center justify-center overflow-hidden bg-gradient-to-br from-rose-50 via-white to-cyan-50 py-20 sm:py-24 md:py-28"
		>
			<FloatingShapes />
			<div className="mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8 xl:max-w-[1400px] 2xl:max-w-[1600px]">
				<div className="grid items-center gap-12 sm:gap-16 md:gap-20 lg:grid-cols-2 lg:gap-24 xl:gap-28 2xl:gap-32">
					<motion.div
						className="flex flex-col justify-center space-y-6 md:space-y-8 xl:space-y-10"
						variants={{
							hidden: { opacity: 0 },
							visible: {
								opacity: 1,
								transition: {
									staggerChildren: 0.15,
									delayChildren: 0.2,
								},
							},
						}}
						initial="hidden"
						animate="visible"
					>
						<motion.div
							variants={{
								hidden: { opacity: 0, y: 30 },
								visible: {
									opacity: 1,
									y: 0,
									transition: {
										duration: 0.7,
										ease: [0.25, 0.46, 0.45, 0.94],
									},
								},
							}}
						>
							<h1 className="font-black text-4xl text-gray-900 leading-none tracking-tight sm:text-5xl md:text-6xl lg:text-7xl xl:text-8xl 2xl:text-9xl">
								{t("hero.greeting").toUpperCase()},
								<br />
								I'M{" "}
								<span className="bg-gradient-to-r from-purple-600 via-cyan-600 to-rose-600 bg-clip-text text-transparent">
									{t("hero.name")}
								</span>
								!
							</h1>
						</motion.div>

						<motion.div
							variants={{
								hidden: { opacity: 0, y: 30 },
								visible: {
									opacity: 1,
									y: 0,
									transition: {
										duration: 0.7,
										ease: [0.25, 0.46, 0.45, 0.94],
									},
								},
							}}
						>
							<p className="max-w-2xl font-medium text-gray-700 text-lg leading-relaxed sm:text-xl md:text-2xl lg:text-3xl xl:text-3xl 2xl:text-4xl">
								{t("hero.role")}
							</p>
						</motion.div>
						<SocialLinks />
					</motion.div>

					{/* Profile Card */}
					<motion.div
						className="relative flex items-center justify-center"
						variants={{
							hidden: { opacity: 0, y: 30 },
							visible: {
								opacity: 1,
								y: 0,
								transition: {
									duration: 0.7,
									ease: [0.25, 0.46, 0.45, 0.94],
								},
							},
						}}
						initial="hidden"
						animate="visible"
					>
						<div className="relative">
							<div className="-top-4 -left-4 absolute h-[28rem] w-96 rotate-2 rounded-3xl border-4 border-gray-900 bg-rose-200 sm:h-[32rem] sm:w-[26rem]" />

							<div className="relative flex h-[28rem] w-96 flex-col items-center justify-center overflow-hidden rounded-3xl border-4 border-gray-900 bg-gradient-to-br from-cyan-50 to-rose-50 p-8 text-center shadow-[8px_8px_0px_0px_rgba(17,24,39,1)] sm:h-[32rem] sm:w-[26rem] sm:p-10">
								<div className="mb-8 flex h-36 w-36 items-center justify-center rounded-full border-4 border-gray-900 bg-gradient-to-br from-purple-400 via-cyan-400 to-rose-400 shadow-lg sm:h-40 sm:w-40">
									<span className="font-black text-5xl text-white sm:text-6xl">
										BE
									</span>
								</div>

								<h3 className="mb-4 font-black text-2xl text-gray-900 sm:text-3xl">
									{t("hero.role").toUpperCase()}
								</h3>

								<p className="mb-8 font-medium text-base text-gray-600 leading-relaxed sm:text-lg">
									{t("hero.description")}
								</p>

								<div className="grid w-full grid-cols-2 gap-4 sm:gap-5">
									<StatCard
										value={HERO_STATS.projects}
										label={t("hero.stats.projects")}
									/>
									<StatCard
										value={HERO_STATS.experience}
										label={t("hero.stats.experience")}
									/>
								</div>
							</div>

							<motion.div
								className="-top-2 -right-2 absolute flex h-14 w-14 items-center justify-center rounded-full border-4 border-gray-900 bg-gradient-to-br from-yellow-400 to-orange-500 text-xl shadow-lg sm:h-16 sm:w-16"
								animate={{
									rotate: [0, 10, -10, 0],
									scale: [1, 1.1, 1],
								}}
								transition={{
									duration: 3,
									repeat: Number.POSITIVE_INFINITY,
									ease: "easeInOut",
								}}
								style={{ willChange: "transform" }}
							>
								<Zap className="h-7 w-7 text-white sm:h-8 sm:w-8" />
							</motion.div>
						</div>
					</motion.div>
				</div>
			</div>
			<ScrollIndicator />
		</section>
	);
}

// src/lib/components/Hero.svelte
<script lang="ts">
	import { m } from '$lib/paraglide/messages.js';
	import { SOCIAL_LINKS } from '$lib/constants';
</script>

<section class="hero" id="hero">
	<div class="hero-container">
		<div class="hero-content">
			<h1 class="hero-title">
				{m.hero_greeting()}
				<br />
				<span class="gradient-text">{m.hero_name()}</span>!
			</h1>

			<p class="hero-role">{m.hero_role()}</p>

			<!-- Social Links -->
			<div class="social-links">
				{#each SOCIAL_LINKS as social (social.name)}
					<a
						href={social.href}
						target="_blank"
						rel="noopener noreferrer"
						class="social-link {social.hoverClass}"
						aria-label={social.label}
					>
						{#if social.name === 'GitHub'}
							<svg
								xmlns="http://www.w3.org/2000/svg"
								width="24"
								height="24"
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								stroke-width="2"
								stroke-linecap="round"
								stroke-linejoin="round"
							>
								<path
									d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"
								></path>
								<path d="M9 18c-4.51 2-5-2-7-2"></path>
							</svg>
						{:else if social.name === 'LinkedIn'}
							<svg
								xmlns="http://www.w3.org/2000/svg"
								width="24"
								height="24"
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								stroke-width="2"
								stroke-linecap="round"
								stroke-linejoin="round"
							>
								<path
									d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"
								></path>
								<rect width="4" height="12" x="2" y="9"></rect>
								<circle cx="4" cy="4" r="2"></circle>
							</svg>
						{:else if social.name === 'Email'}
							<svg
								xmlns="http://www.w3.org/2000/svg"
								width="24"
								height="24"
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								stroke-width="2"
								stroke-linecap="round"
								stroke-linejoin="round"
							>
								<rect width="20" height="16" x="2" y="4" rx="2"></rect>
								<path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"></path>
							</svg>
						{/if}
					</a>
				{/each}
			</div>
		</div>
	</div>

	<!-- Scroll Indicator -->
	<button
		aria-label={m.hero_scroll()}
		class="scroll-indicator"
		onclick={() => document.getElementById('about')?.scrollIntoView({ behavior: 'smooth' })}
	>
		<svg
			fill="none"
			height="40"
			stroke="currentColor"
			stroke-linecap="round"
			stroke-linejoin="round"
			stroke-width="3"
			viewBox="0 0 24 24"
			width="40"
			xmlns="http://www.w3.org/2000/svg"
		>
			<path d="m6 9 6 6 6-6"></path>
		</svg>
	</button>
</section>

<style lang="scss">
	// Variables
	$color-gray-700: #374151;
	$color-gray-900: #111827;
	$color-white: #ffffff;
	$color-cyan-50: #ecfeff;
	$color-cyan-600: #0891b2;
	$color-rose-50: #fff1f2;
	$color-rose-600: #e11d48;
	$color-purple-600: #9333ea;
	$color-blue-600: #2563eb;

	$breakpoint-sm: 640px;
	$breakpoint-md: 768px;
	$breakpoint-lg: 1024px;
	$breakpoint-xl: 1280px;
	$breakpoint-2xl: 1536px;

	$transition-fast: 0.2s ease;

	// Hero Section
	.hero {
		position: relative;
		min-height: 100vh;
		display: flex;
		align-items: center;
		justify-content: center;
		overflow: hidden;
		background: linear-gradient(to bottom right, $color-rose-50, $color-white, $color-cyan-50);
		padding: 5rem 0 2rem;

		@media (min-width: $breakpoint-sm) {
			padding: 6rem 0;
		}

		@media (min-width: $breakpoint-md) {
			padding: 7rem 0;
		}
	}

	// Container
	.hero-container {
		position: relative;
		z-index: 1;
		width: 100%;
		max-width: 1280px;
		margin: 0 auto;
		padding: 0 1rem;

		@media (min-width: $breakpoint-sm) {
			padding: 0 1.5rem;
		}

		@media (min-width: $breakpoint-lg) {
			padding: 0 2rem;
		}

		@media (min-width: $breakpoint-xl) {
			max-width: 1400px;
		}

		@media (min-width: $breakpoint-2xl) {
			max-width: 1600px;
		}
	}

	// Hero Content
	.hero-content {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		text-align: center;
		gap: 1.5rem;

		@media (min-width: $breakpoint-md) {
			gap: 2rem;
		}

		@media (min-width: $breakpoint-xl) {
			gap: 2.5rem;
		}
	}

	.hero-title {
		font-size: 2.25rem;
		font-weight: 900;
		color: $color-gray-900;
		line-height: 1;
		letter-spacing: -0.025em;

		@media (min-width: $breakpoint-sm) {
			font-size: 3rem;
		}

		@media (min-width: $breakpoint-md) {
			font-size: 3.75rem;
		}

		@media (min-width: $breakpoint-lg) {
			font-size: 4.5rem;
		}

		@media (min-width: $breakpoint-xl) {
			font-size: 6rem;
		}

		@media (min-width: $breakpoint-2xl) {
			font-size: 8rem;
		}
	}

	.gradient-text {
		background: linear-gradient(to right, $color-purple-600, $color-cyan-600, $color-rose-600);
		-webkit-background-clip: text;
		background-clip: text;
		color: transparent;
	}

	.hero-role {
		max-width: 42rem;
		font-size: 1.125rem;
		font-weight: 500;
		color: $color-gray-700;
		line-height: 1.625;

		@media (min-width: $breakpoint-sm) {
			font-size: 1.25rem;
		}

		@media (min-width: $breakpoint-md) {
			font-size: 1.5rem;
		}

		@media (min-width: $breakpoint-lg) {
			font-size: 1.875rem;
		}

		@media (min-width: $breakpoint-2xl) {
			font-size: 2.25rem;
		}
	}

	// Social Links
	.social-links {
		display: flex;
		gap: 1rem;
	}

	.social-link {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 3.5rem;
		height: 3.5rem;
		background-color: $color-white;
		border: 3px solid $color-gray-900;
		border-radius: 0.75rem;
		color: $color-gray-900;
		box-shadow: 4px 4px 0px 0px $color-gray-900;
		transition: $transition-fast;

		@media (min-width: $breakpoint-md) {
			border-width: 4px;
		}

		&:hover {
			transform: translateY(-4px);
			box-shadow: 6px 6px 0px 0px $color-gray-900;
		}

		&:active {
			transform: translateY(0);
			box-shadow: 2px 2px 0px 0px $color-gray-900;
		}

		&.github:hover {
			background-color: $color-gray-900;
			color: $color-white;
		}

		&.linkedin:hover {
			background-color: $color-blue-600;
			color: $color-white;
		}

		&.email:hover {
			background-color: $color-cyan-600;
			color: $color-white;
		}
	}

	// Scroll Indicator
	.scroll-indicator {
		position: absolute;
		bottom: 2rem;
		left: 50%;
		transform: translateX(-50%);
		background: none;
		border: none;
		cursor: pointer;
		color: $color-gray-900;
		transition: $transition-fast;

		&:hover {
			transform: translateX(-50%) translateY(4px);
		}
	}
</style>
